BoxLayout:
    orientation: "horizontal"

    FolderTreeWidget:
        id: tree
        size_hint: (0.3, 1)
        root_label: "Images"
        db: app.db

    BoxLayout:
        size_hint: (0.7, 1)
        orientation: "vertical"
        Label:
            size_hint: (1, 0.1)
            text: tree.selected_path
        ImageList:
            db: app.db
            selected_path: tree.selected_path
