BoxLayout:
    orientation: "horizontal"

    FolderTreeWidget:
        id: tree
        size_hint: (0.3, 1)
        root_label: "Images"
        db: app.db

    BoxLayout:
        size_hint: (0.7, 1)
        orientation: "vertical"
        Button:
            text: "Test 1"
        Image:
            source: app.test_img
        Button:
            text: "Test 2"
        Button:
            text: tree.selected_path
        Button:
            text: "Test 3"
